# Name of site
name: low fequency

# Tagline
description: ¯\_(ツ)_/¯

# URL of avatar
avatar: https://lough.dev/images/pfp-icon.png

# footer icon for each username
footer-links:
  dribbble:
  email: drew@lough.tech
  facebook: #DrewLough
  flickr:
  github: drewLo
  instagram:
  linkedin: /drewlough/
  pinterest:
  rss: # type anything here for a working RSS icon
  twitter: 
  stackoverflow: users/6402386/dlo
  youtube: 

# Disqus shortname (not username) for comments
disqus: lough-tech

# Google Analytics
google_analytics: UA-78356005-4

# Website URL for Sitemap.xml and RSS feed
url: https://lough.dev

# If hosting site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT the User repository (http://yourusername.github.io)
# add baseurl here, like this: "/repository-name"
baseurl: ""

# No need to change any of the configuration flags below
permalink: /:title/

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
